---
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/starkandwayne/concourse-tutorial.git
- name: resource-app
  type: git
  source:
    uri: https://github.com/sandeepbupathi08/node-expressserver.git

- name: resource-deploy-web-app
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: true

jobs:
- name: job-deploy-app
  public: true
  serial: true
  plan:
  - get: resource-tutorial
  - get: resource-app
    trigger: true
  - put: resource-deploy-web-app
    params:
      manifest: resource-app/manifest.yml
      path: resource-app
